[shell]
program = "/bin/zsh"
args = [ "-l" , "-c" , "tmux attach || tmux" ]

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings=[
    {key="C", mods="Control|Shift", action="Copy"},
    {key="V", mods="Control", action="Paste"}
    ]
